<template>
    <div class="loading">
        <div class="loadingio-spinner-gear-lrcmths3fjp">
            <div class="ldio-lagrve6fh4">
                <div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: "loading",
    data() {
        return {};
    }
};
</script>

<style type="text/css">
.loading {
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 1000000;
    opacity: 0;
    visibility: hidden;
    transition: all 0.3s ease;
    background-color: rgba(0, 0, 0, 0.53);
}
.loading.show {
    opacity: 1;
    visibility: visible;
}

.loading .loadingio-spinner-gear-lrcmths3fjp {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%) scale(0.5);
}
@keyframes ldio-lagrve6fh4 {
    0% {
        transform: rotate(0deg);
    }

    50% {
        transform: rotate(22.5deg);
    }

    100% {
        transform: rotate(45deg);
    }
}

.ldio-lagrve6fh4 > div {
    transform-origin: 100px 100px;
    animation: ldio-lagrve6fh4 0.2s infinite linear;
}

.ldio-lagrve6fh4 > div div {
    position: absolute;
    width: 22px;
    height: 152px;
    background: #85a2b6;
    left: 100px;
    top: 100px;
    transform: translate(-50%, -50%);
}

.ldio-lagrve6fh4 > div div:nth-child(1) {
    width: 120px;
    height: 120px;
    border-radius: 50%;
}

.ldio-lagrve6fh4 > div div:nth-child(6) {
    width: 80px;
    height: 80px;
    background: #f1f2f3;
    border-radius: 50%;
}

.ldio-lagrve6fh4 > div div:nth-child(3) {
    transform: translate(-50%, -50%) rotate(45deg);
}

.ldio-lagrve6fh4 > div div:nth-child(4) {
    transform: translate(-50%, -50%) rotate(90deg);
}

.ldio-lagrve6fh4 > div div:nth-child(5) {
    transform: translate(-50%, -50%) rotate(135deg);
}

.loadingio-spinner-gear-lrcmths3fjp {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
}

.ldio-lagrve6fh4 {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0;
    /* see note above */
}

.ldio-lagrve6fh4 div {
    box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>